### ISSUE TITLE
Failed to initialize native library

### ISSUE THREAD

**Issue by KBepo** [BlinkID/blinkid-react-native#42]
I keep getting this error when running microblink inside my application. Licences are ok, everything is OK haven't changed code nor updated anything. Today it started crashing.

Runing adb error logcat gives tons of random errors which aren't really part of my App rather part of Microblink native module. Is there any way to solve this?

**Comment by culoi** [comment]
Hi @KBepo 

Are you able to share errors from the logcat? 

That would help us greatly to check where the issue is.

Regards

**Comment by KBepo** [comment]
This is what I'm getting:

`04-05 13:47:16.091  3887  5737 E Parcel  : Class not found when unmarshalling: com.microblink.metadata.MetadataSettings$ImageMetadataSettings
04-05 13:47:16.091  3887  5737 E Parcel  : java.lang.ClassNotFoundException: com.microblink.metadata.MetadataSettings$ImageMetadataSettings
04-05 13:47:16.091  3887  5737 E Parcel  : 	at java.lang.Class.classForName(Native Method)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at java.lang.Class.forName(Class.java:324)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at android.os.Parcel.readParcelable(Parcel.java:2358)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at android.os.Parcel.readValue(Parcel.java:2264)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at android.os.BaseBundle.getString(BaseBundle.java:920)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at android.content.Intent.getStringExtra(Intent.java:6183)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2695)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2157)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6349)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6127)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3997)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at android.os.Binder.execTransact(Binder.java:453)
04-05 13:47:16.091  3887  5737 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.microblink.metadata.MetadataSettings$ImageMetadataSettings
04-05 13:47:16.091  3887  5737 E Parcel  : 	at java.lang.Class.classForName(Native Method)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-05 13:47:16.091  3887  5737 E Parcel  : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-05 13:47:16.091  3887  5737 E Parcel  : 	... 16 more
04-05 13:47:16.091  3887  5737 E Parcel  : Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`
